-- USER SQL
CREATE USER LEMON IDENTIFIED BY 1234 
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP;

-- QUOTAS
ALTER USER LEMON QUOTA 10M ON USERS;

-- ROLES
GRANT DBA TO LEMON ;
GRANT CONNECT TO LEMON ;
GRANT RESOURCE TO LEMON ;

-- SYSTEM PRIVILEGES

