DROP SEQUENCE BOARDID;
DROP SEQUENCE USERID;
DROP TABLE COMMENTS;
DROP TABLE BOARD;
DROP TABLE ADEUSER;

-- ADEUSER
CREATE TABLE ADEUSER
(
  ID NUMBER NOT NULL 
, NAME VARCHAR2(20) NOT NULL 
, EMAIL VARCHAR2(45) NOT NULL 
, PW VARCHAR2(45) NOT NULL 
, CONSTRAINT ADEUSER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE USERID INCREMENT BY 1 START WITH 1;
-- ½ÃÄö½º
CREATE TRIGGER ADEUSER_TRG 
BEFORE INSERT ON ADEUSER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USERID.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

-- BOARD
CREATE TABLE BOARD 
(
  USERID NUMBER NOT NULL 
, ID NUMBER NOT NULL 
, TITLE VARCHAR2(45) NOT NULL
, CONTENT VARCHAR2(200) 
, IMG BLOB 
, CREATETIME TIMESTAMP DEFAULT SYSDATE NOT NULL 
, CONSTRAINT BOARD_PK PRIMARY KEY 
  (
    USERID, ID
  )
  ENABLE 
);

CREATE SEQUENCE BOARDID INCREMENT BY 1 START WITH 1;
-- ½ÃÄö½º
CREATE TRIGGER BOARD_TRG 
BEFORE INSERT ON BOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT BOARDID.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

ALTER TABLE BOARD
ADD CONSTRAINT BOARD_FK1 FOREIGN KEY
(
  USERID
)
REFERENCES ADEUSER
(
  ID 
)
ON DELETE CASCADE ENABLE;

-- COMMENTS
CREATE TABLE COMMENTS 
(
  USERID NUMBER NOT NULL 
, BOARDID NUMBER NOT NULL 
, ID NUMBER NOT NULL 
, WRITERID NUMBER NOT NULL 
, CONTENT VARCHAR2(200) NOT NULL 
, DEPTH NUMBER DEFAULT 0 
, PARENTID NUMBER 
, CONSTRAINT COMMENTS_PK PRIMARY KEY 
  (
    USERID, BOARDID, ID 
  )
  ENABLE 
);

-- COMMENT'S FKS
ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_FK1 FOREIGN KEY
(
  WRITERID 
)
REFERENCES ADEUSER
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_FK2 FOREIGN KEY
(
  USERID 
)
REFERENCES ADEUSER
(
  ID 
)
ON DELETE CASCADE ENABLE;

ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENTS_FK3 FOREIGN KEY
(
  BOARDID 
)
REFERENCES BOARD
(
  ID 
)
ON DELETE CASCADE ENABLE;

INSERT INTO ADEUSER (NAME, EMAIL, PW) VALUES ('hello1', 'hi@naver.com', '1234');
INSERT INTO ADEUSER (NAME, EMAIL, PW) VALUES ('hello2', 'hun@naver.com', '1234');

INSERT INTO "LEMON"."BOARD" (USERID, TITLE, CONTENT) VALUES ('1', 'Ice Cream', 'It is very delicious!');
INSERT INTO "LEMON"."BOARD" (USERID, TITLE, CONTENT) VALUES ('1', 'Coffee', 'I like it');
INSERT INTO "LEMON"."BOARD" (USERID, TITLE, CONTENT) VALUES ('2', 'Cake', 'this is chocolate cake.');